### PR TITLE
Format Advent of Code 2019 using Black

### PR DESCRIPTION
**Pull request by nsmaciej**
I just thought I might tidy up your code a bit.

### CODE REVIEW

**Review by EoinDavey — CHANGES_REQUESTED** [review]
Will pull if 10.py isn't included, it is obtuse on purpose

**Comment by nsmaciej** [comment]
Done.

**Comment by jesse-ashmore** [comment]
Can we get some traction on this please I've been waiting 2 years for this to be merged

**Review by EoinDavey — APPROVED** [review]

**Comment by EoinDavey** [comment]
Approved. Thanks for patience with this

**Pull request merged**
